//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCloudAdmin.CSCloudLogServerProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSCloudLogEntry", Namespace="http://schemas.datacontract.org/2004/07/CSCloud.Data")]
    [System.SerializableAttribute()]
    public partial class CSCloudLogEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CSCloudAdmin.CSCloudLogServerProxy.CSCloudSeverity SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CSCloudAdmin.CSCloudLogServerProxy.CSCloudSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CSCloudSeverity", Namespace="http://schemas.datacontract.org/2004/07/CSCloud.Enums")]
    public enum CSCloudSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WARNING = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INFO = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CSCloudLogServerProxy.ICSCloudLogService")]
    public interface ICSCloudLogService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICSCloudLogService/Log")]
        void Log(CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry logEntry);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICSCloudLogService/Log")]
        System.Threading.Tasks.Task LogAsync(CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry logEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICSCloudLogService/GetLog", ReplyAction="http://tempuri.org/ICSCloudLogService/GetLogResponse")]
        CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry[] GetLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICSCloudLogService/GetLog", ReplyAction="http://tempuri.org/ICSCloudLogService/GetLogResponse")]
        System.Threading.Tasks.Task<CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry[]> GetLogAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSCloudLogServiceChannel : CSCloudAdmin.CSCloudLogServerProxy.ICSCloudLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSCloudLogServiceClient : System.ServiceModel.ClientBase<CSCloudAdmin.CSCloudLogServerProxy.ICSCloudLogService>, CSCloudAdmin.CSCloudLogServerProxy.ICSCloudLogService {
        
        public CSCloudLogServiceClient() {
        }
        
        public CSCloudLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSCloudLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSCloudLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSCloudLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Log(CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry logEntry) {
            base.Channel.Log(logEntry);
        }
        
        public System.Threading.Tasks.Task LogAsync(CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry logEntry) {
            return base.Channel.LogAsync(logEntry);
        }
        
        public CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry[] GetLog() {
            return base.Channel.GetLog();
        }
        
        public System.Threading.Tasks.Task<CSCloudAdmin.CSCloudLogServerProxy.CSCloudLogEntry[]> GetLogAsync() {
            return base.Channel.GetLogAsync();
        }
    }
}
