//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCloudClient.CSCloudLogServerProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CSCloudLogServerProxy.ICSCloudLogService")]
    public interface ICSCloudLogService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICSCloudLogService/Log")]
        void Log(CSCloud.Data.CSCloudLogEntry logEntry);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICSCloudLogService/Log")]
        System.Threading.Tasks.Task LogAsync(CSCloud.Data.CSCloudLogEntry logEntry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICSCloudLogService/GetLog", ReplyAction="http://tempuri.org/ICSCloudLogService/GetLogResponse")]
        CSCloud.Data.CSCloudLogEntry[] GetLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICSCloudLogService/GetLog", ReplyAction="http://tempuri.org/ICSCloudLogService/GetLogResponse")]
        System.Threading.Tasks.Task<CSCloud.Data.CSCloudLogEntry[]> GetLogAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICSCloudLogServiceChannel : CSCloudLogServerProxy.ICSCloudLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSCloudLogServiceClient : System.ServiceModel.ClientBase<CSCloudLogServerProxy.ICSCloudLogService>, CSCloudLogServerProxy.ICSCloudLogService {
        
        public CSCloudLogServiceClient() {
        }
        
        public CSCloudLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CSCloudLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSCloudLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CSCloudLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Log(CSCloud.Data.CSCloudLogEntry logEntry) {
            base.Channel.Log(logEntry);
        }
        
        public System.Threading.Tasks.Task LogAsync(CSCloud.Data.CSCloudLogEntry logEntry) {
            return base.Channel.LogAsync(logEntry);
        }
        
        public CSCloud.Data.CSCloudLogEntry[] GetLog() {
            return base.Channel.GetLog();
        }
        
        public System.Threading.Tasks.Task<CSCloud.Data.CSCloudLogEntry[]> GetLogAsync() {
            return base.Channel.GetLogAsync();
        }
    }
}
