//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCloud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public Command()
        {
            this.CommandParameters = new HashSet<CommandParameter>();
        }
    
        public int id { get; set; }
        public int ClientID { get; set; }
        public string Result { get; set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<CommandParameter> CommandParameters { get; set; }
    }
}
