//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCloud.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSCloudEntities : DbContext
    {
        public CSCloudEntities()
            : base("name=CSCloudEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Command> Commands { get; set; }
        public virtual DbSet<CommandParameter> CommandParameters { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<vwCommand> vwCommands { get; set; }
    }
}
