//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCloud.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCommand
    {
        public string ClientName { get; set; }
        public string CommandResult { get; set; }
        public string CommandCode { get; set; }
        public Nullable<System.DateTime> CommandDate { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
    }
}
